// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./src/components/common/AdminMenu.vue')['default']
    Ckeditor: typeof import('./src/components/editor/Ckeditor.vue')['default']
    AdminMenuLayout: typeof import('./src/components/layoutWrapper/AdminMenuLayout.vue')['default']
    DefaultLayout: typeof import('./src/components/layoutWrapper/DefaultLayout.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    Markdown: typeof import('./src/components/editor/Markdown.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    MyButton: typeof import('./src/components/common/MyButton.vue')['default']
    Pagin: typeof import('./src/components/common/Pagin.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/common/Upload.vue')['default']
  }
}
