// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Ckeditor: typeof import('./src/components/editor/Ckeditor.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    DefaultLayout: typeof import('./src/components/layoutWrapper/DefaultLayout.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Markdown: typeof import('./src/components/editor/Markdown.vue')['default']
    Mkeditor: typeof import('./src/components/editor/Mkeditor.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/common/Upload.vue')['default']
  }
}
