/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./src/components/common/AdminMenu.vue')['default']
    AdminMenuLayout: typeof import('./src/components/layoutWrapper/AdminMenuLayout.vue')['default']
    Ckeditor: typeof import('./src/components/editor/Ckeditor.vue')['default']
    CropperAndUpload: typeof import('./src/components/common/CropperAndUpload.vue')['default']
    DefaultLayout: typeof import('./src/components/layoutWrapper/DefaultLayout.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    FullWidthLayout: typeof import('./src/components/layoutWrapper/FullWidthLayout.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    Markdown: typeof import('./src/components/editor/Markdown.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    MyButton: typeof import('./src/components/common/MyButton.vue')['default']
    MyLabel: typeof import('./src/components/common/MyLabel.vue')['default']
    Oauth: typeof import('./src/components/Oauth.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/common/Upload.vue')['default']
  }
}
